spring:
  application:
    name: planner-todo
  config:
    # для считывания своего файла конфигурации
    import: configserver:http://localhost:8888
  profiles:
    active: micro, todo, utils, logging, kafka