spring:
  application:
    name: planner-users
  config:
    # для считывания своего файла конфигурации
    import: configserver:http://localhost:8888
  profiles:
    active: micro, utils, logging, kafka, keycloak